# Generated by Django 3.1.1 on 2020-09-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
